name: Sincronizacion Automatizada AutoLogi

on:
  schedule:
    # Se ejecuta dos veces al día (Hora UTC)
    # 12:00 UTC = 7:00 AM COT (UTC-5)
    # 03:00 UTC = 10:00 PM COT (UTC-5)
    - cron: '0 12,3 * * *'
  workflow_dispatch: # Permite ejecución manual desde la pestaña Actions

jobs:
  run-sync:
    runs-on: ubuntu-latest
    steps:
      - name: Descargar codigo del repositorio
        uses: actions/checkout@v3

      - name: Configurar entorno de Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Instalar librerias necesarias
        run: pip install pandas sqlalchemy psycopg2-binary gspread gspread-dataframe google-auth

      - name: Ejecutar script de sincronizacion
        env:
          DB_URL: ${{ secrets.DB_URL }}
          GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
        run: python sync_supabase.py

